@echo off
::
:: run.bat — Run the etlp binary on Windows.
::
:: Usage:
::   run.bat [--daemon] [--install-autostart] [--remove-autostart]
::           [--binary PATH] [--data-dir DIR] [--dry-run] [--help]
::
:: Autostart uses the Windows Startup folder (shell:startup).
:: For a truly silent background launch use run-silent.vbs.

setlocal enabledelayedexpansion

:: ── Defaults ─────────────────────────────────────────────────────────────────

set "DAEMON=0"
set "INSTALL_AUTOSTART=0"
set "REMOVE_AUTOSTART=0"
set "DRY_RUN=0"
set "BINARY="
set "DATA_DIR="

:: ── Argument parsing ──────────────────────────────────────────────────────────

:parse_args
if "%~1"==""                      goto :after_args
if /i "%~1"=="--daemon"           ( set "DAEMON=1"           & shift & goto :parse_args )
if /i "%~1"=="--install-autostart"( set "INSTALL_AUTOSTART=1"& shift & goto :parse_args )
if /i "%~1"=="--remove-autostart" ( set "REMOVE_AUTOSTART=1" & shift & goto :parse_args )
if /i "%~1"=="--dry-run"          ( set "DRY_RUN=1"          & shift & goto :parse_args )
if /i "%~1"=="--binary"           ( set "BINARY=%~2"         & shift & shift & goto :parse_args )
if /i "%~1"=="--data-dir"         ( set "DATA_DIR=%~2"       & shift & shift & goto :parse_args )
if /i "%~1"=="--help"             goto :show_help
if /i "%~1"=="-h"                 goto :show_help
echo [error] Unknown option: %~1
goto :show_help

:after_args

:: ── Locate binary ─────────────────────────────────────────────────────────────

if not "%BINARY%"=="" (
    if not exist "%BINARY%" (
        echo [error] Binary not found: %BINARY%
        exit /b 1
    )
    goto :binary_found
)

:: Search candidate paths
for %%p in (
    "%~dp0..\target\release\etlp.exe"
    "%~dp0..\target\x86_64-pc-windows-msvc\release\etlp.exe"
    "C:\Program Files\etlp\etlp.exe"
) do (
    if exist %%p ( set "BINARY=%%~p" & goto :binary_found )
)
echo [error] etlp.exe not found. Build it first with scripts\build-windows-binary.bat
exit /b 1

:binary_found

:: ── Helpers ───────────────────────────────────────────────────────────────────

set "STARTUP_FOLDER=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "VBS_PATH=%STARTUP_FOLDER%\etlp-silent.vbs"

:: ── Actions ───────────────────────────────────────────────────────────────────

if "%DRY_RUN%"=="1" echo [dry-run] No changes will be made.

if "%INSTALL_AUTOSTART%"=="1" goto :install_autostart
if "%REMOVE_AUTOSTART%"=="1"  goto :remove_autostart
goto :run

:: ── Install autostart ─────────────────────────────────────────────────────────
:install_autostart
echo      Installing autostart: %VBS_PATH%

if "%DRY_RUN%"=="1" (
    echo [dry-run] Would write VBScript launcher to %VBS_PATH%
    goto :eof
)

if not exist "%STARTUP_FOLDER%" mkdir "%STARTUP_FOLDER%"

:: Build argument string for VBScript
set "EXTRA_ARGS="
if not "%DATA_DIR%"=="" set "EXTRA_ARGS= --data-dir ""%DATA_DIR%"""

(
echo ' etlp silent launcher — auto-generated by run.bat
echo ' Runs etlp.exe without a console window on Windows startup.
echo Set oWS = WScript.CreateObject^("WScript.Shell"^)
echo oWS.Run """"%BINARY%""""%EXTRA_ARGS%"", 0, False
) > "%VBS_PATH%"

echo         Done: etlp will start silently at next login.
echo              To run immediately: wscript "%VBS_PATH%"
goto :eof

:: ── Remove autostart ──────────────────────────────────────────────────────────
:remove_autostart
if not exist "%VBS_PATH%" (
    echo [skip] Autostart entry not found ^(%VBS_PATH%^)
    goto :eof
)
echo      Removing autostart: %VBS_PATH%
if "%DRY_RUN%"=="0" del /f /q "%VBS_PATH%"
echo         Done: autostart removed.
goto :eof

:: ── Run ───────────────────────────────────────────────────────────────────────
:run
set "ARGS="
if not "%DATA_DIR%"=="" set "ARGS=--data-dir "%DATA_DIR%""

if "%DAEMON%"=="1" (
    echo      Starting etlp in background…
    if "%DRY_RUN%"=="0" (
        start /b "" "%BINARY%" %ARGS%
        echo         Done: etlp is running in the background.
    ) else (
        echo [dry-run] start /b "" "%BINARY%" %ARGS%
    )
) else (
    echo      Starting etlp…
    if "%DRY_RUN%"=="0" (
        "%BINARY%" %ARGS%
    ) else (
        echo [dry-run] "%BINARY%" %ARGS%
    )
)
goto :eof

:: ── Help ──────────────────────────────────────────────────────────────────────
:show_help
echo.
echo run.bat -- Run the etlp binary or manage Windows autostart
echo.
echo USAGE
echo   run.bat [OPTIONS]
echo.
echo OPTIONS
echo   --daemon              Run in background (no console window)
echo   --install-autostart   Add silent VBScript launcher to Startup folder
echo   --remove-autostart    Remove the Startup folder entry
echo   --binary PATH         Path to etlp.exe (auto-detected if absent)
echo   --data-dir DIR        Override data directory
echo   --dry-run             Print actions without executing
echo   --help, -h            Show this help
echo.
exit /b 0
