name: CI Rust

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-rust-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-fast-lint:
    name: Rust Fast Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Pre-fetch Rust dependencies
        run: cargo fetch --locked

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy linter
        run: cargo clippy --workspace --all-targets --frozen -- -D warnings

  rust-build-test:
    name: Rust Build And Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Pre-fetch Rust dependencies
        run: cargo fetch --locked

      - name: Run tests
        run: cargo test --workspace --frozen
